### PR TITLE
Add files for hexagon intro to GNSS book as well as complete summary …

### PR DESCRIPTION
**Pull request by yairroorda**
My very first pull request, let's hope this works :). I made md files for all the chapters in the Hexagon GNSS intro book and went ahead and completed chapter 9 mostly to get used to the workflow

### CODE REVIEW

**Comment by alexandre-bry** [comment]
Thanks! Everything looks fine, I only have a few things to say:

- Important: to add this to the website, you also need to add the names of the files you want to add to [`docs/books.txt`](https://github.com/ZokszY/GEO1003-Shared_Notes/blob/main/docs/books.txt)
- Not really important: it would be better if the file names were at least coherent among one book, although it's not really useful and just me being annoying so you can dismiss that
- More important?: your markdown syntax should work but your line breaks are quite unconventional:
  - Conventionally there should be one line break before and after each heading
  - Single line breaks between sentences in paragraphs are ok but in the middle of sentences it's a bit strange

So first add the files to [`docs/books.txt`](https://github.com/ZokszY/GEO1003-Shared_Notes/blob/main/docs/books.txt) and I'll merge your pull request. We'll see if we get any problem related to the syntax when building the files, but I guess it should work.

**Comment by yairroorda** [comment]
Did the tweaks, should be better now

**Comment by alexandre-bry** [comment]
Yes looks perfect! I merge and it should be online in a few minutes

**Comment by alexandre-bry** [comment]
Haha I realized too late you put "contents" instead of "content" in books.txt so it didnt work. I fixed it with a new commit

**Pull request merged**
